### DISCUSSION TITLE
comment-changes:  CI fails with code 64 and message "Tag v1.2.3 does not seem to exist."

### DISCUSSION THREAD

**Discussion by kevinmatthes** [kevinmatthes/aeruginous-rs#1029] [Q&A] [answered]
In my CI, I use the following workflow:

```yml
name: comment-changes

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.head_ref }}

      - uses: fregante/setup-git-user@v2.0.1

      - run: |
          rustup update
          cargo install aeruginous --all-features
          aeruginous comment-changes -d ::= -f ron -k -o changelog.d/ -T "v$(cat .version)"
          git add changelog.d/
          git commit -m 'Create summary of recent changes'
          git push
```

This workflow shall create a single fragment with all changes since the last release, tag `v1.2.3`, and push it to the HEAD branch of the respective PR.  But when I run it, I always receive exit code 64 and the following message:

```
Tag v1.2.3 does not seem to exist.
```

What do I do wrong?

**Comment by kevinmatthes** [comment, marked as answer]
The problem can be resolved by checking out the repository with the following setup:

```yml
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
```

The key point is the line `fetch-depth: 0` which adjusts the number of commits being checked out.  By default, `actions/checkout` will only checkout 1 commit (the one referred to by HEAD) in order to improve the performance, especially in repositories with many commits.  Unfortunately, the last commit is not necessarily one with the queried tag, in your case `v1.2.3`.  Thus, Aeruginous cannot find the tag because it has no access to the respective commit.
