### DISCUSSION TITLE
cffreference:  Processing remote CITATION.cff in CI

### DISCUSSION THREAD

**Discussion by kevinmatthes** [kevinmatthes/aeruginous-rs#1081] [Q&A] [answered]
In my CI, I would like to assemble my CITATION.cff from a basic set of citation data as well as a list of references containing the processed CITATION.cff files of the projects I use as dependencies.  By doing so, I would like to keep my references up-to-date in case that some of the dependency projects should have published new releases.  How can I automate this task with Aeruginous?

**Comment by kevinmatthes** [comment, marked as answer]
Aeruginous offers reading from `stdin` for its `cffreference` mode.  Thus, you can just `curl` the *raw* input CITATION.cff into Aeruginous and `cffreference` it as usual:

```
curl https://raw.githubusercontent.com/kevinmatthes/aeruginous-rs/main/CITATION.cff | aeruginous cffreference -o CITATION.cff
```

For convenience, there is also a GitHub Action available which automatically `curl`s CITATION.cff files of projects hosted on GitHub into Aeruginous; you can bind it as follows.

```yml
      - uses: kevinmatthes/aeruginous-rs/curl-cffref@v3.3.0
        with:
          branch: # branch
          repository: # user/repository
```
